services:
  nginx_service:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      - my_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      - my_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      - my_network

  
networks:
  my_network: